# Generated by Django 5.1.5 on 2026-03-25 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["user", "level", "is_best"], name="submission_user_level_best_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["user", "created_at"], name="submission_user_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_best", True)), fields=("user", "level"), name="uniq_best_submission_per_user_level"
            ),
        ),
    ]
